// Icons the AI may use, by name. A fixed list keeps the choice small
// and the bundle light (all of lucide would be huge). No React here.
export const iconNames = [
  'sparkles',
  'zap',
  'shield',
  'lock',
  'globe',
  'rocket',
  'heart',
  'star',
  'check',
  'clock',
  'cloud',
  'code',
  'database',
  'layers',
  'layout',
  'lightbulb',
  'message',
  'chart',
  'users',
  'settings',
  'search',
  'bell',
  'calendar',
  'credit-card',
  'file',
  'mail',
  'phone',
  'smartphone',
  'trending-up',
  'wallet',
  'home',
  'folder',
  'image',
  'music',
  'video',
  'book',
  'award',
  'target',
  'gift',
  'map-pin',
] as const

export type IconName = (typeof iconNames)[number]
