// Icon name (from the AI) → lucide icon component
import {
  AwardIcon,
  BellIcon,
  BookIcon,
  CalendarIcon,
  ChartColumnIcon,
  CheckIcon,
  ClockIcon,
  CloudIcon,
  CodeIcon,
  CreditCardIcon,
  DatabaseIcon,
  FileTextIcon,
  FolderIcon,
  GiftIcon,
  GlobeIcon,
  HeartIcon,
  HouseIcon,
  ImageIcon,
  LayersIcon,
  LayoutDashboardIcon,
  LightbulbIcon,
  LockIcon,
  MailIcon,
  MapPinIcon,
  MessageSquareIcon,
  MusicIcon,
  PhoneIcon,
  RocketIcon,
  SearchIcon,
  SettingsIcon,
  ShieldCheckIcon,
  SmartphoneIcon,
  SparklesIcon,
  StarIcon,
  TargetIcon,
  TrendingUpIcon,
  UsersIcon,
  VideoIcon,
  WalletIcon,
  ZapIcon,
  type LucideIcon,
} from 'lucide-react'
import type { IconName } from './icon-names'

const icons: Record<IconName, LucideIcon> = {
  sparkles: SparklesIcon,
  zap: ZapIcon,
  shield: ShieldCheckIcon,
  lock: LockIcon,
  globe: GlobeIcon,
  rocket: RocketIcon,
  heart: HeartIcon,
  star: StarIcon,
  check: CheckIcon,
  clock: ClockIcon,
  cloud: CloudIcon,
  code: CodeIcon,
  database: DatabaseIcon,
  layers: LayersIcon,
  layout: LayoutDashboardIcon,
  lightbulb: LightbulbIcon,
  message: MessageSquareIcon,
  chart: ChartColumnIcon,
  users: UsersIcon,
  settings: SettingsIcon,
  search: SearchIcon,
  bell: BellIcon,
  calendar: CalendarIcon,
  'credit-card': CreditCardIcon,
  file: FileTextIcon,
  mail: MailIcon,
  phone: PhoneIcon,
  smartphone: SmartphoneIcon,
  'trending-up': TrendingUpIcon,
  wallet: WalletIcon,
  home: HouseIcon,
  folder: FolderIcon,
  image: ImageIcon,
  music: MusicIcon,
  video: VideoIcon,
  book: BookIcon,
  award: AwardIcon,
  target: TargetIcon,
  gift: GiftIcon,
  'map-pin': MapPinIcon,
}

// Unknown or missing names draw nothing instead of crashing
export function Icon({
  name,
  className,
}: {
  name?: string | null
  className?: string
}) {
  const Component = name ? icons[name as IconName] : undefined
  return Component ? <Component className={className} aria-hidden /> : null
}
