// Icon name (from the AI) → lucide icon component
import {
  AwardIcon,
  BellIcon,
  BookIcon,
  CalendarIcon,
  ChartColumnIcon,
  CheckIcon,
  ClockIcon,
  CloudIcon,
  CodeIcon,
  CreditCardIcon,
  DatabaseIcon,
  FileTextIcon,
  FolderIcon,
  GiftIcon,
  GlobeIcon,
  HeartIcon,
  HouseIcon,
  ImageIcon,
  LayersIcon,
  LayoutDashboardIcon,
  LightbulbIcon,
  LockIcon,
  MailIcon,
  MapPinIcon,
  MessageSquareIcon,
  MusicIcon,
  PhoneIcon,
  RocketIcon,
  SearchIcon,
  SettingsIcon,
  ShieldCheckIcon,
  SmartphoneIcon,
  SparklesIcon,
  StarIcon,
  TargetIcon,
  TrendingUpIcon,
  UsersIcon,
  VideoIcon,
  WalletIcon,
  ZapIcon,
  type LucideIcon,
  HeadphonesIcon,
  WineIcon,
  MartiniIcon,
  CoffeeIcon,
  UtensilsIcon,
  TruckIcon,
  CarIcon,
  PlaneIcon,
  TrainIcon,
  BikeIcon,
  MapIcon,
  CompassIcon,
  TicketIcon,
  CameraIcon,
  MicIcon,
  RadioIcon,
  TvIcon,
  Gamepad2Icon,
  BookOpenIcon,
  GraduationCapIcon,
  BriefcaseIcon,
  BuildingIcon,
  StoreIcon,
  ShoppingCartIcon,
  ShoppingBagIcon,
  PackageIcon,
  TagIcon,
  PercentIcon,
  DollarSignIcon,
  BanknoteIcon,
  PiggyBankIcon,
  ChartPieIcon,
  ActivityIcon,
  TrophyIcon,
  MedalIcon,
  FlagIcon,
  BookmarkIcon,
  WrenchIcon,
  HammerIcon,
  CpuIcon,
  ServerIcon,
  WifiIcon,
  LaptopIcon,
  MonitorIcon,
  TerminalIcon,
  GitBranchIcon,
  BotIcon,
  BrainIcon,
  WandSparklesIcon,
  PaletteIcon,
  BrushIcon,
  PenToolIcon,
  LeafIcon,
  SunIcon,
  MoonIcon,
  FlameIcon,
  DropletIcon,
  SnowflakeIcon,
  MountainIcon,
  TreePineIcon,
  FlowerIcon,
  DogIcon,
  CatIcon,
  BabyIcon,
  UserIcon,
  UserPlusIcon,
  SmileIcon,
  ThumbsUpIcon,
  MessageCircleIcon,
  SendIcon,
  Share2Icon,
  LinkIcon,
  DownloadIcon,
  UploadIcon,
  RefreshCwIcon,
  InfinityIcon,
  PuzzleIcon,
  KeyIcon,
  FingerprintIcon,
  EyeIcon,
  HeartPulseIcon,
  StethoscopeIcon,
  PillIcon,
  DumbbellIcon,
  BedIcon,
  PartyPopperIcon,
  CakeIcon,
  ShirtIcon,
  GemIcon,
  CrownIcon,
  CoinsIcon,
  ReceiptIcon,
  ClipboardListIcon,
  ListChecksIcon,
  LayoutGridIcon,
  BlocksIcon,
  BoxIcon,
  SlidersHorizontalIcon,
  GaugeIcon,
  TimerIcon,
  HourglassIcon,
  CalendarCheckIcon,
  EarthIcon,
  AnchorIcon,
  ShipIcon,
  TentIcon,
  SofaIcon,
} from 'lucide-react'
import type { IconName } from './icon-names'

const icons: Record<IconName, LucideIcon> = {
  sparkles: SparklesIcon,
  zap: ZapIcon,
  shield: ShieldCheckIcon,
  lock: LockIcon,
  globe: GlobeIcon,
  rocket: RocketIcon,
  heart: HeartIcon,
  star: StarIcon,
  check: CheckIcon,
  clock: ClockIcon,
  cloud: CloudIcon,
  code: CodeIcon,
  database: DatabaseIcon,
  layers: LayersIcon,
  layout: LayoutDashboardIcon,
  lightbulb: LightbulbIcon,
  message: MessageSquareIcon,
  chart: ChartColumnIcon,
  users: UsersIcon,
  settings: SettingsIcon,
  search: SearchIcon,
  bell: BellIcon,
  calendar: CalendarIcon,
  'credit-card': CreditCardIcon,
  file: FileTextIcon,
  mail: MailIcon,
  phone: PhoneIcon,
  smartphone: SmartphoneIcon,
  'trending-up': TrendingUpIcon,
  wallet: WalletIcon,
  home: HouseIcon,
  folder: FolderIcon,
  image: ImageIcon,
  music: MusicIcon,
  video: VideoIcon,
  book: BookIcon,
  award: AwardIcon,
  target: TargetIcon,
  gift: GiftIcon,
  'map-pin': MapPinIcon,
  headphones: HeadphonesIcon,
  wine: WineIcon,
  martini: MartiniIcon,
  coffee: CoffeeIcon,
  utensils: UtensilsIcon,
  truck: TruckIcon,
  car: CarIcon,
  plane: PlaneIcon,
  train: TrainIcon,
  bike: BikeIcon,
  map: MapIcon,
  compass: CompassIcon,
  ticket: TicketIcon,
  camera: CameraIcon,
  mic: MicIcon,
  radio: RadioIcon,
  tv: TvIcon,
  'gamepad-2': Gamepad2Icon,
  'book-open': BookOpenIcon,
  'graduation-cap': GraduationCapIcon,
  briefcase: BriefcaseIcon,
  building: BuildingIcon,
  store: StoreIcon,
  'shopping-cart': ShoppingCartIcon,
  'shopping-bag': ShoppingBagIcon,
  package: PackageIcon,
  tag: TagIcon,
  percent: PercentIcon,
  'dollar-sign': DollarSignIcon,
  banknote: BanknoteIcon,
  'piggy-bank': PiggyBankIcon,
  'chart-pie': ChartPieIcon,
  activity: ActivityIcon,
  trophy: TrophyIcon,
  medal: MedalIcon,
  flag: FlagIcon,
  bookmark: BookmarkIcon,
  wrench: WrenchIcon,
  hammer: HammerIcon,
  cpu: CpuIcon,
  server: ServerIcon,
  wifi: WifiIcon,
  laptop: LaptopIcon,
  monitor: MonitorIcon,
  terminal: TerminalIcon,
  'git-branch': GitBranchIcon,
  bot: BotIcon,
  brain: BrainIcon,
  'wand-sparkles': WandSparklesIcon,
  palette: PaletteIcon,
  brush: BrushIcon,
  'pen-tool': PenToolIcon,
  leaf: LeafIcon,
  sun: SunIcon,
  moon: MoonIcon,
  flame: FlameIcon,
  droplet: DropletIcon,
  snowflake: SnowflakeIcon,
  mountain: MountainIcon,
  'tree-pine': TreePineIcon,
  flower: FlowerIcon,
  dog: DogIcon,
  cat: CatIcon,
  baby: BabyIcon,
  user: UserIcon,
  'user-plus': UserPlusIcon,
  smile: SmileIcon,
  'thumbs-up': ThumbsUpIcon,
  'message-circle': MessageCircleIcon,
  send: SendIcon,
  'share-2': Share2Icon,
  link: LinkIcon,
  download: DownloadIcon,
  upload: UploadIcon,
  'refresh-cw': RefreshCwIcon,
  infinity: InfinityIcon,
  puzzle: PuzzleIcon,
  key: KeyIcon,
  fingerprint: FingerprintIcon,
  eye: EyeIcon,
  'heart-pulse': HeartPulseIcon,
  stethoscope: StethoscopeIcon,
  pill: PillIcon,
  dumbbell: DumbbellIcon,
  bed: BedIcon,
  'party-popper': PartyPopperIcon,
  cake: CakeIcon,
  shirt: ShirtIcon,
  gem: GemIcon,
  crown: CrownIcon,
  coins: CoinsIcon,
  receipt: ReceiptIcon,
  'clipboard-list': ClipboardListIcon,
  'list-checks': ListChecksIcon,
  'layout-grid': LayoutGridIcon,
  blocks: BlocksIcon,
  box: BoxIcon,
  'sliders-horizontal': SlidersHorizontalIcon,
  gauge: GaugeIcon,
  timer: TimerIcon,
  hourglass: HourglassIcon,
  'calendar-check': CalendarCheckIcon,
  earth: EarthIcon,
  anchor: AnchorIcon,
  ship: ShipIcon,
  tent: TentIcon,
  sofa: SofaIcon,
}

// Unknown or missing names draw nothing instead of crashing
export function Icon({
  name,
  className,
}: {
  name?: string | null
  className?: string
}) {
  const Component = name ? icons[name as IconName] : undefined
  return Component ? <Component className={className} aria-hidden /> : null
}
